CREATE TABLE SHIPWRECK(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  CONDITION VARCHAR(255),
  DEPTH INT,
  LATITUDE DOUBLE,
  LONGITUDE DOUBLE,
  YEAR_DISCOVERED INT
);
